sudo: required
dist: trusty
language: node_js
node_js: "6"
branches:
  only:
    - develop
script:
  - npm test
services:
  - postgresql
env:
  - JWT_SECRET=abcxyz,
  - MAIL_USERNAME=jim.hadi10@gmail.com,
  - MAIL_PASSWORD=75867586,
  - TWILIO_ACCOUNT_SID=AC308c7e589c0578a1372314b4d8d88786
  - TWILIO_AUTH_TOKEN=e5f29d821e7191484cef632e55d34658
before_script:
  - psql -c 'CREATE DATABASE travis;' -U postgres
before_install:
 - export CHROME_BIN=/usr/bin/google-chrome
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
after_success: npm run coverage