sudo: required
dist: trusty
language: node_js
node_js: '6'
branches:
  only:
  - develop
script:
- npm test
services:
- postgresql
env:
  matrix:
  - JWT_SECRET=abcxyz
  - secure: CafXuplCyXxhxeVBVEDJ+N2O7xIyZ6HXbmpWQ/zHcIX2y1hTtoSMTT1Jprr4leoMwkLubV5MM5yq5JBzuYtBKvnSXMq9kaA5rVOOF05dZvGAtAOsmiLDJPd029RSXDMhzQfiHMU0kIwGLMc2SYkvj2dkdWeV7sE/FzrozP5tlwVvCCwTaJ0yBnOc4LKoEhA89nQj05/+elUqVNeGbfCt99nsgkewSkyJ2cylDgf/dNsCLgLTZSltQkOIXs6odY82xerJa/qPH4J2H9n0i26nQXi53OqY4WoCoIKqg/y16VAtChPKB2Qj7QDPGfL2h/mrtZOWcmPfKgaJh0UsbCwTIzu2Zp/Pt6gq/NLAxxzVAVnFjqLl9X8cRO9uchQwieUigVz0vhIlyQPTpTrnRFUeX8eIFQu/milxJjEi4C1aBEw2G2g7k8LHo1bzEze0LAbTAqBfV0reqaONL8n7KZLRwEzW/rWDru1kmCfiGIrld6GRQ2huCa8yqBxVk0GAhI+k9+AfmpVVl+cZ6BqlwIdFia4qsvMIm36LGTuCzxMuzzV45A2h2aV1sczcWwnVhrCYkbCucl2Y96Vtk4qF55dagDolwMe/UMTfY7C53i20ls92et1PRNprg316KMlfY63HVT7ABc623+MQiOksn294d1B0pHDzRneTgsAGTOpaj6s=
  - secure: HqCBDPCynJgOdIBVMUmbgvf9GoD3dmqifqKrnzRjXZ2U1nEjT7mnPSgMMQaBl+hZMETphND974C49H6+pkgpciKCHDlDh3SfdKev25Z9DvIKikLzb+N3ZA0oO8WS2xqhPSShHosnwAIWVEYl0n4z/0nqIdNIArPaGqshye7KAeNSJIFBjAUeeyM6/AcEYVo6CScG2Kqr3c6nJZc+JNGbhzvIH2wVxmjMH6lUfpdyiQ9stSkLsrEZcBglY4M7qighWT+YW8o0IBwyDaCLFFmUS6lCPO0gno5m0aRrHNdHorrIMHG4//A6Yn0A9SgwQsRkgfwkDmSm/HYscTE4yIQUue3+z0cLF4sQ4S7td2fPrSK5UPnriaD/bik74Vq2FCsiC6fOih+usfDqfSwyVjPR70sMpP2US6kTZrM0lHwDohOEyMDYNhGa6jhMLoI2M30qIg6O8OuimTLY5vHSNMgotulNNBmxA+JXFx7/j66gY75BPyeBW97d/DEDl5Usv1TiWGdngRdSUlZbjt9ttD6Yh+HFLclvT4Ssmx66scQ0BbU/WKCiJbX7A1YF6V1F7aWmwMPuPOBSUUjsB8JWgGwDtCZLj+5YPgjP6mDo+3fik2aFYa53MaMilLZHq7XxW3XL2HxaN7JF5kFzXuyt42kMygbRpaVf1ghO5qH4JqbgQmk=
before_script:
- psql -c 'CREATE DATABASE travis;' -U postgres
before_install:
- export CHROME_BIN=/usr/bin/google-chrome
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
after_success: npm run coverage
